Repository 2DegreesInvesting/PACTA_analysis, pull requests merged in 2020-10, with the labels that each got.

#163 Detect and use more packages
  deduplicate/load-and-attach-r-packages.R
Labels: bug

#181 don't change encoding option because it's dangerous and unpredictable
  web_tool_script_1.R
  web_tool_script_3.R
Labels: duplicate

#182 stop using paste0 to manually build file paths
  0_global_functions.R
  0_web_functions.R
  web_tool_script_1.R
  web_tool_script_2.R
  web_tool_script_3.R
Labels: duplicate

#236 Fin data add ext sectors
  0_portfolio_input_check_functions.R
  data/sector_bridge.csv
  web_tool_script_2.R
Labels: enhancement

#239 re-introduce missing st parameters plus new IPR data
  web_tool_script_3.R
Labels: enhancement

#244 set ST shock year to 2030
  web_tool_script_3.R
Labels: enhancement

#252 fix function call to create_int_rep
  web_tool_script_3.R
Labels: bug

#272 Rm unnecessary files
  0_web_functions.R
  web_tool_script_1.R
Labels: enhancement

#279 Enhance run-web-tool to show upstream-branch and status
  bin/run-web-tool
  bin/show-upstream-and-status-at
  bin/show-upstream-and-status-at-pacta-repos
Labels: infrastructure

#241 parameterize the portfolio name when using the web tool
  bin/README.md
  bin/run-r-scripts
Labels: web tool

#283 Move path of logs
  .gitignore
  0_global_functions.R
  0_web_functions.R
  web_tool_script_1.R
  working_dir/00_Log_Files/.gitignore..txt
  working_dir/00_Log_Files/.gitkeep.txt
Labels: enhancement, infrastructure

#287 Surface path write log
  0_global_functions.R
  0_portfolio_input_check_functions.R
  0_web_functions.R
Labels: infrastructure
